### ISSUE TITLE
Downloadable documentation for C++ bindings

### ISSUE THREAD

**Issue by terminatorul** [KhronosGroup/Khronosdotorg#116]
Hello

There is currently no way to download documentation for the C++ bindings. (I have to clone the repository and build it myself if I want an offline copy).

Could you release a download file for C++ bindings documentation ? Maybe a .chm file, in the Releases page of the bindings project on github ...

Thank you,
Timothy Madden

**Comment by oddhack** [comment]
If you're referring to a specific API's C++ binding github project, then the issue should probably be moved to that repository.

**Comment by terminatorul** [comment]
Created https://github.com/KhronosGroup/OpenCL-CLHPP/issues/117
