### ISSUE TITLE
Your subdomain being hijacked

### ISSUE THREAD

**Issue by sabungtrans** [KhronosGroup/Khronosdotorg#124]
Hi There
Looks like your website is being hacked!!!
Someone is hijacking your website under subdomain public.khronos.org
Kindly fix that or remove the subdomain from your DNS in order to fix it.
Example:
http://public.khronos.org/za/www-tubidy-com-music-2020/sughbreng
This is strictly prohibited and against the international law due to illegal content (mp3 songs).
Please kindly fix this as soon as possible!
Thank You.

This is very important to forward this message to technical team.

**Comment by kpet** [comment]
Thanks for flagging this, this has now been brought to the attention of the right people.

**Comment by Khronoswebmaster** [comment]
Thank you for this notification. We have notified the hosting company and removed an incorrect DNS record.
