### ISSUE TITLE
Feature in Companies Publicly Supporting OpenXR

### ISSUE THREAD

**Issue by ConnectBhawna** [KhronosGroup/Khronosdotorg#139]
## Introduction 
When a user accesses the OpenXR website, they are directed to the "Companies Publicly Supporting OpenXR" section. However, currently, clicking on a specific company does not result in any action. I would like to add a hover feature to allow users to interact with and access information about each company by hovering over their respective logos.

## Screenshot
![Screenshot from 2023-04-25 22-55-23](https://user-images.githubusercontent.com/81790585/234355541-3ebaeca8-3d35-4ff3-9773-0a00dd55e517.png)

**Comment by outofcontrol** [comment]
Correct. No links at this time as it is a single graphic. We will take this request into consideration for a future version of the OpenXR landing page. Thank you @ConnectBhawna
