### ISSUE TITLE
Error in OpenCL 1.2 reference pages 

### ISSUE THREAD

**Issue by StrahinjaStamenkovic** [KhronosGroup/Khronosdotorg#141]
Inside the [reference pages](https://registry.khronos.org/OpenCL/sdk/1.2/docs/man/xhtml/) for OpenCL 1.2, specifically **_clSetEventCallback_**, under the errors section, the following is stated as explanation for **CL_INVALID_VALUE**:

> **CL_INVALID_VALUE** if _pfn_event_notify_ is **NULL** or if _command_exec_callback_type_ is not **CL_COMPLETE**.

And if we look at the [PDF](https://registry.khronos.org/OpenCL/specs/opencl-1.2.pdf) of the OpenCL 1.2 Specification it includes **CL_SUBMITTED** and **CL_RUNNING**:

> **CL_INVALID_VALUE** if _pfn_event_notify_ is NULL or if _command_exec_callback_type_ is not **CL_SUBMITTED**, **CL_RUNNING** or **CL_COMPLETE**

The same [reference pages](https://registry.khronos.org/OpenCL/sdk/2.0/docs/man/xhtml/) but now for OpenCL 2.0 also include **CL_SUBMITTED** and **CL_RUNNING**:

> **CL_INVALID_VALUE** if _pfn_event_notify_ is NULL or if _command_exec_callback_type_ is not **CL_SUBMITTED**, **CL_RUNNING** or **CL_COMPLETE**.

So this is probably an error in the reference pages for OpenCL 1.2 and should be fixed

**Comment by outofcontrol** [comment]
Please post issues under their related repository. In this case:

https://github.com/KhronosGroup/OpenCL-Docs

Thank you.

**Comment by oddhack** [comment]
BTW I normally just 'Transfer issue' when I see something like this.

**Comment by outofcontrol** [comment]
Oops, I can do that? Learned something new today. Apologies @StrahinjaStamenkovic

**Comment by StrahinjaStamenkovic** [comment]
My mistake, posted the issue in the correct repository @outofcontrol
