### ISSUE TITLE
python Build.py error 

### ISSUE THREAD

**Issue by xqch1983** [KhronosGroup/Khronosdotorg#36]
when i run python Build.py , the errors occured, can you help me fix it,thanks.

E:\OpenVX\openvx_sample>**python Build.py --os Windows --arch=64 --conf=Debug --gen="Visual Studio 14" --cpp "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe" --rebuild="TRUE"**

cmake E:\OpenVX\openvx_sample -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=E:\OpenVX\openvx_sample\install\Win\x64\${BUILD_TYPE} -DBUILD_X64=1 -G "Visual Studio 14 Win64" -DCMAKE_CXX_COMPILER=
-- ===== OpenVX version: 1.1 =====
-- The C compiler identification is MSVC 19.0.24210.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- The CXX compiler identification is MSVC 19.0.24210.0
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:174 (add_subdirectory):
  **_add_subdirectory given source "sample-c++" which is not an existing_** 
  directory.

-- Configuring incomplete, errors occurred!
See also "E:/OpenVX/openvx_sample/build/Win/x64/CMakeFiles/CMakeOutput.log".
DEVENV OpenVX.sln /build Debug /project INSTALL

Microsoft Visual Studio 2015 Version 14.0.25420.1.
Copyright (C) Microsoft Corp. All rights reserved.

The following files were specified on the command line:

        OpenVX.sln

These files could not be found and will not be loaded.

**Comment by outofcontrol** [comment]
You will need to post any issues within the repository that has the code you are running. This repository, Khronosdotorg is for HTML webpages only. No code there. Closing the issue.
