### ISSUE TITLE
Vulkan SDK and Resources

### ISSUE THREAD

**Issue by Andreyogld3d** [KhronosGroup/Khronosdotorg#42]
Hello!
We can add the Adreno SDK for Vulkan in section "SDK"
https://developer.qualcomm.com/download/software

this link we can add in section "Resources"
http://gpuopen.com/gaming-product/vulkan/

Thanks!

**Comment by outofcontrol** [comment]
Would you be able to make a pull request for this?

**Comment by Andreyogld3d** [comment]
Hello, *outofcontrol*
ok, i created Pull requests
