### ISSUE TITLE
intel open source driver is invalid in resources.md

### ISSUE THREAD

**Issue by meilihao** [KhronosGroup/Khronosdotorg#51]
OS : Linux chen-PC 4.9.0-deepin9-amd64 #1 SMP PREEMPT Deepin 4.9.29-4 (2017-07-17) x86_64 GNU/Linux
Hardware : Intel Corporation HD Graphics 530

how to get intel  driver for vulkan, the link of intel open source driver in resources.md is invalid.

**Comment by Khronoswebmaster** [comment]
Link updated.
