### ISSUE TITLE
Changes to OpenCL tool description

### ISSUE THREAD

**Issue by AnastasiaStulova** [KhronosGroup/Khronosdotorg#73]
This issue is to gather updates for tools.

- Update the link to SPIRV-LLVM Translator: rename converter -> translator. The old link should still be present but some explanation should be provided that it's deprecated.
- Add link to LLVM+Clang and explain OpenCL + AMD GPU support.

**Comment by AnastasiaStulova** [comment]
Add section on tool documentation: we can link Clang OpenCL manual and add SPIRV friendly document too.

Would it make sense to add links to public talks explaining tools development? (For example video recordings from LLVM conferences).

**Comment by keryell** [comment]
Perhaps we could add this to the agenda of the next tooling meeting?

**Comment by AnastasiaStulova** [comment]
I suggest to restructure this into the following two pages:

1. **Vendors information**. This will contain information about vendors that support OpenCL. Suggested substructure:
- Driver
- Tooling: Compiler, Libraries, Debuggers, Profiles
- Tutorials
- Vendor specific tools and frameworks (ML libraries, inference engines, etc)
- Vendor agnostic information: tools (common open source components), tutorials, frameworks.

2. **Open source tools** . Will contain detailed description of tools and their interactions. This can be expanded from the following blog: https://www.khronos.org/blog/new-and-enhanced-opencl-open-source-tools-resources

**Comment by Khronoswebmaster** [comment]
Users currently have difficulty finding the current one resource page. If we split the resource page into two, we should find a solution to make it easier for users to find these pages. Or stick with one page.

**Comment by pjaaskel** [comment]
Let me know if you need something related to pocl.

**Comment by pjaaskel** [comment]
Can you add something like: "Portable Computing Language (POCL) - an implementation framework for diverse device type OpenCL platforms which utilizes the upstream Clang/LLVM as a kernel compilation backbone. The upstream POCL project currently supports various CPUs, open source ASIPs, NVIDIA GPUs (via libcuda) among other devices in the same OpenCL context." Thanks!

**Comment by Khronoswebmaster** [comment]
@AnastasiaStulova is this issue still needed?

**Comment by AnastasiaStulova** [comment]
I think we should close it as the page has been updated already. Thanks.
