### ISSUE TITLE
Authoritarian Political CoC should be replaced.

### ISSUE THREAD

**Issue by LordStreetguru** [KhronosGroup/Khronosdotorg#74]
I find the contributor covenant very dangerous, as well as it's author's ideology. It may not seem bad on the surface, however it's goal seems to be gaining control over the TAB, which then by the Contributor Covenant's rules allow the TAB to gatekeep projects based on it's ideology. It's why it uses vague terms like "inclusivity" and "empathy", and why it forces itself on devs and maintainers.

The same type of activist who advocates for it are currently working to frame someone on the Linux TAB board as a "Rape Apologist" for simply questioning if a report(s) on assault statistics were accurate. 

<https://twitter.com/_sagesharp_/status/1042769399596437504>

Here is a long twitter thread detailing the authors radical views and objection to Meritocracy, and confirming it is a political document.
https://twitter.com/nickmon1112/status/1041668315947708416
-
-
There are many non repressive Code of Conducts, 

The Code of Merit is a solid document for keeping a community functioning without resorting to authoritarianism.
http://code-of-merit.org/

As is the "No Code of Conduct" approach, which respects users' basic morality and common sense, rather than spelling out the same thing in many vague and specific words, as well as requiring those vague things be enforced, can simply be summed up as "Write good code, don't be a jerk"
https://github.com/domgetter/NCoC

When asked for comment Richard Stallman of GNU fame stated that he
"Disapproves of strict codes of conduct, They feel ridged and repressive to me" 
-
-
Some devs simply want nothing to do with modern politics or disagree so strongly that they are willing to change the license of their code so that it may be removed from projects over this code of conduct, or at least their personal future versions I suppose.

Having such a divisive and powerful code of conduct may scare devs from ever getting involved with the project. 
https://lulz.com/linux-devs-threaten-killswitch-coc-controversy-1252/

**
an FAQ has been added to that code of conduct's page, further illustrating the author's intentions. 

https://github.com/ContributorCovenant/contributor_covenant/blob/4c5be31375a655469efc2914c348a1c49fdabea6/content/faq.md

What should I do if I have been accused of violating the code of conduct?

The first step when dealing with accusations of violation of the code of conduct is to deal with it in a professional manner. Do not respond with sarcasm, attack the code of conduct or its enforcement, or the accuser. ***Calmly focus on the evidence of what happened, work to understand the damage you may have caused, and examine how your intentions may have inadvertently caused harm.*** The more you stick to the facts of what happened, and demonstrate your willingness to work with the administrators evaluate the claims, the better. Most importantly, trust the project maintainers to act in a fair and just manner.

The highlighted line seems to indicate a guilty until proven innocent approach to me.  

"What is so wrong that white males dominate a certain profession?"
In addition the author seems to believe that "white men" have an advantage when contributing to a project, despite projects being collaborative efforts and freely available for anyone to contribute to since the dawn of FOSS movements. 

In addition the author may not believe in free speech, given past statements and this bit from the FAQ, as "hate group" is undefined like many vague terms in the contributor covenant.

"(with the obvious exception of hate groups.)"

and directly contradicts herself with the following lines

"Doesn't adopting a code of conduct make a contributor subject to removal from a project for a simple mistake, holding an unpopular belief.."

"The Contributor Covenant specifically states that behavior, actions, and communications outside the scope of the project cannot be considered violations of the code of conduct"

**Comment by LordStreetguru** [comment]
As a further update to the points, the author of the CoC has previously called for a "Transphobic Maintainer" in 2015 to be removed from a project. Just further proof of the true intentions of the Contributor Covenant.

https://github.com/opal/opal/issues/941

**Comment by LordStreetguru** [comment]
The CERN CoC, which appears to be very similar when it comes to it's radical left views, was just used to remove a scientist from participating at CERN(may have been employed), because he explained why there aren't more women in physics using data, instead of accepting that it's because of "discrimination"

https://twitter.com/CERNpress/status/1046423269841281024

https://cds.cern.ch/record/2240689/files/BrochureCodeofConductEN.pdf?

Here's what I assume is a translated version of the actual presentation.
https://drive.google.com/file/d/1c_NyUhOZ8erdqU2AGZJZtNfFeA91Kefj/edit

**Comment by LordStreetguru** [comment]
It appears the Linux version of that CoC will be updated/changed in a few ways at least,
https://www.phoronix.com/scan.php?page=news_item&px=Linux-CoC-Changes-Inbound

**Comment by dneto0** [comment]
Hi.  Thanks for taking the time to file this.  Clearly you care about the issue and about the future of .  I'd like to take more time to consider your thoughts before replying.

Before I go further, I'd like to understand better.  You say you are concerned about a takeover of the "TAB".  What is the TAB you're talking about?  I don't know of a Khronos TAB.

**Comment by LordStreetguru** [comment]
> 
> Before I go further, I'd like to understand better. You say you are concerned about a takeover of the "TAB". What is the TAB you're talking about? I don't know of a Khronos TAB.

The Technical Advisory Board is more Linux Specific, those are the group people who review complaints and decide on actions for that community, instead of the project leaders directly I think..

Without a board like that it falls to:
"unacceptable behavior may be reported by contacting the project team [email]" Or Project Leader I assume.

Where in the project leader/maintainers must still use the contributor covenant, rather than being free to use whatever CoC they want, or lack there of. Which is where the authoritarian part comes in.

"Project maintainers who do not follow or enforce the Code of Conduct in good
faith may face temporary or permanent repercussions as determined by other
members of the project’s leadership."

By it's own rules, if say someone wanted to come and directly contribute for FOSS ray tracing tech to be built into vulkan, but didn't want to use the Contributor Covenant, they wouldn't be allowed in strictly speaking, or on the extreme side even if they did it on their own website/git hub the CoC may not allow their code into the project, that's more tin foil hat though I suppose.

And if that's not the case, and it doesn't have to be enforced on all contributors/maintainers, then why even use the Covenant to begin with?
-
-
I have asked the author to define some of the terms used in it, but have yet to get a response. 
https://github.com/ContributorCovenant/contributor_covenant/issues/598

**Comment by keryell** [comment]
OK, I think you are talking about https://github.com/KhronosGroup/Khronosdotorg/blob/master/CODE_OF_CONDUCT.md

It was not clear to me how it was related to this git repository, since there was no mention of a concrete file...
