### ISSUE TITLE
Vulkan section of github.khronos.org needs update for new repos

### ISSUE THREAD

**Issue by mikew-lunarg** [KhronosGroup/Khronosdotorg#79]
The current state of the Vulkan section does not reflect a reorg of the Khronos repos, such as the
- creation of Vulkan-Headers, Vulkan-Loader, Vulkan-Tools, Vulkan-ValidationLayers
- deprecation of Vulkan-LoaderAndValidationLayers and Vulkan-Samples.

**Comment by outofcontrol** [comment]
Thanks Mike. Did you want to create a PR? 

https://github.com/KhronosGroup/khronosgroup.github.io

**Comment by oddhack** [comment]
AFAICT this was fixed at some point as all @mikew-lunarg's points have been addressed.
