### ISSUE TITLE
vulkaninfo/vulkaninfo.c:3339: failed with VK_ERROR_INITIALIZATION_FAILED

### ISSUE THREAD

**Issue by Pixelec** [KhronosGroup/Khronosdotorg#81]
Having this issue and the same in my own code since removed DKMS and installed AKMOD.
(I'm working on a fresh install at the moment in fact).

Is that due to akmod in general? Or for this kernel version (4.19.4-300.fc29.x86_64)?
Do I have to come back to DKMS or have I another solution?

Installed :
xorg-x11-drv-nvidia-340xx akmod-nvidia-340xx libX11-devel libXext-devel mesa-libGL mesa-libGL-devel vulkan vulkan-devel vulkan-tools

Got an Nvidia GT710.

**Comment by liam-middlebrook** [comment]
Hi,

In the future for problems with your driver installation you'll probably get a quicker response if you report the issue on NVIDIA's [DevTalk forums](https://devtalk.nvidia.com/default/board/98/linux/) or send an email to `linux-bugs [at] nvidia.com`.

The release 340 series doesn't include support for Vulkan, which was added in the release 364 series. You'll want to upgrade to a newer driver series.

**Comment by Pixelec** [comment]
Ok, looks like they changed it, I had 340 drivers with DKMS before, and that was working, but they can have changed their policy... Ok, if you are sure this is not related to vulkan but only to the driver, let me know, and I'll close this issue.

**Comment by Pixelec** [comment]
Resolved, only due to akmod, I had to install the generic one, not the 340 version.
