### ISSUE TITLE
How is the SYCL page built?

### ISSUE THREAD

**Issue by keryell** [KhronosGroup/Khronosdotorg#87]
While trying to edit https://www.khronos.org/sycl/ with https://github.com/KhronosGroup/Khronosdotorg/pull/86 I do not know where the 3rd part of the page (after the second blue horizontal rule and where the figure is) comes from.
It is not in https://github.com/KhronosGroup/Khronosdotorg/blob/master/api/sycl/bluebox.md

**Comment by outofcontrol** [comment]
Blue box ix in GitHub here. The rest of the content is maintained in the CMS.
