### ISSUE TITLE
Arm OpenCL

### ISSUE THREAD

**Issue by youngestuser** [KhronosGroup/Khronosdotorg#90]
Hi,
    Where can I get the RAM OpenCL SDK?

**Comment by Khronoswebmaster** [comment]
Did you mean the Arm OpenCL SDK?

**Comment by youngestuser** [comment]
yes,sorry for spelling Arm into RAM

**Comment by TomOlson** [comment]
Some good information here although it's a year old: 

https://community.arm.com/developer/tools-software/graphics/f/discussions/9417/mali-opencl-sdk-not-found

In particular see Pete Harris's reply.

**Comment by youngestuser** [comment]
@TomOlson  Thank you very much ! It helps me a lot!

**Comment by TomOlson** [comment]
Glad I could help - good luck with your projects! If that answers the immediate question, please close the issue.

**Comment by TomOlson** [comment]
Oops, wrong button...
